### ISSUE TITLE
DharmaVariable.generate doesn't work as expected ?

### ISSUE THREAD

**Issue by tinduong94** [MozillaSecurity/dharma#13]
Hi,

While trying dharma, I was wondering how can I declare variables with only one definition in the grammars. For instance with the following grammar:

```
%section% := value

test :=
    !test! = +dictObject+

dictObject :=
    {}

%section% := variable

test :=
    @test@ = new +dictObject+;

%section% := variance

main :=
    !test! !test!
```

Will produce this output:

```
test1 = new {};
test1 test1
```

How can we declare test2, test3, ... with just one definition of test in the grammar ?

Looking at the `core/dharma.py`, the DharmaVariable seems to not work as expected to me:

```
    def generate(self, state):
        """Return a random variable if any otherwise create a new default variable."""
        if self.count:
            return "%s%d" % (self.var, random.randint(1, self.count))
        self.count += 1
        var = random.choice(self)
        element_name = "%s%d" % (self.var, self.count)
        self.default = "%s%s%s" % (self.eval(var[0], state), element_name, self.eval(var[1], state))
        return element_name
```

The self.count will never be greater than 1, which makes the random doesn't make sense.

**Comment by posidron** [comment]
That might seem odd, I agree. Though I believe the problem seems to be related in how we started to treat `@`. 

We also removed the instance method to add a new variable from the outside which also incremented `self.count` in that class, hence using `random.randint()` in `generate()` leads to confusion there. But overall I think it made things easier to track and there were no undefined variables in the result.

Different example:

```
%const% VARIANCE_MIN := 4
%const% VARIANCE_MAX := 8

%section% := value

dictContent :=
    a: null
    b: {}

dictObject :=
    {+dictContent+}

testStmnt :=
    !pc_l! = !pc_r!
    !pc_r! = @pc_r@

%section% := variable

pc_l :=
    let @pc_l@ = new +dictObject+;

pc_r :=
    let @pc_r@ = new +dictObject+;

%section% := variance

main :=
    +testStmnt+
```

The `@pc_r@` in the value section should probably create and add a new variable declaration in the output. 

What you are asking for explicitly is not possible at the moment.

PRs are welcome.

**Comment by tinduong94** [comment]
I will take a look on this.

Btw, I don't see the differences when using `@` in your example. 

Input :
```
testStmnt :=
    !pc_l! = !pc_r!
```
Output:
```
let pc_l1 = new {b: {}};
let pc_r1 = new {a: null};
pc_l1 = pc_r1
pc_l1 = pc_r1
pc_l1 = pc_r1
pc_l1 = pc_r1
pc_l1 = pc_r1
pc_l1 = pc_r1
pc_l1 = pc_r1
pc_l1 = pc_r1
```

Input :
```
testStmnt :=
    !pc_l! = !pc_r!
    !pc_r! = @pc_r@
```
Output :
```
let pc_l1 = new {a: null};
let pc_r1 = new {b: {}};
pc_r1 = pc_r1
pc_l1 = pc_r1
pc_l1 = pc_r1
pc_l1 = pc_r1
pc_r1 = pc_r1
```

Did I miss something ?

**Comment by posidron** [comment]
No, see: 

`The @pc_r@ in the value section should probably create and add a new variable assignment in the output.`

Meaning, if @pc_r@ is used, create a new variable, and replace that macro with the variable name. But that's currently not implemented. The original version also didn't have that and simply incremented the variable counter but without making an assignment first. That would be my thought on how to solve your request.

**Comment by shsirk** [comment]
In similar fashion, i solved this issue for my requirement by introducing new constant 
`%const% VARIABLE_MAX := 10`
and few changes in dharma.py!generate to create new variables upto VARIABLE_MAX 

```
   def generate(self, state):
        """Return a random variable if any otherwise create a new default variable."""
        if self.count >= DharmaConst.VARIABLE_MAX:
            return "%s%d" % (self.var, random.randint(1, self.count))
        self.count += 1
        var = random.choice(self)
        element_name = "%s%d" % (self.var, self.count)
        self.default += "%s%s%s\n" % (self.eval(var[0], state), element_name, self.eval(var[1], state))
        return element_name
```
**self.default** to append new var creation. 

works fine for me.

**Comment by posidron** [comment]
That is not recommended. With this change the output from the above example would be:

```
let pc_l2 = new {b: {}};
let pc_r6 = new {a: null};
pc_l1 = pc_r1
pc_r2 = pc_r3
pc_l2 = pc_r4
pc_r5 = pc_r6
```

You see that `pc_l1`, `pc_r3`, `pc_r4`, `pc_r5` are coming out of nowhere and each time you do !varname! it won't reference. I.e.

```
dictContent :=
    a: null
    b: {!pc_l!}
```

In that case the output could even look like this:

```
let pc_l9 = new {b: {pc_l10}};
```

**Comment by posidron** [comment]
I was misreading your post the first time and overlooked the `+=`.  Let me take a closer look and think about this.

**Comment by shsirk** [comment]
One point I missed, in case of recursive definition of variables like 

` var @o_var@ = new Foo(!o_arr!) `

self.eval(var[0], state) and self.eval(var[1], state) needs to be evaluated first before assigning to self.default, otherwise introducing referenced variables as you mentioned in previous post.

updated code - 

```
    def generate(self, state):
        """Return a random variable if any otherwise create a new default variable."""
        if self.count >= DharmaConst.VARIABLE_MAX:
            return "%s%d" % (self.var, random.randint(1, self.count))
        var = random.choice(self)
        _e1 = self.eval(var[0], state)
        _e2 = self.eval(var[1], state)
        self.count += 1
        element_name = "%s%d" % (self.var, self.count)
        self.default += "%s%s%s\n" % (_e1, element_name, _e2)
        return element_name

```
Please confirm if above logic is correct.

**Comment by posidron** [comment]
Thanks @shsirk. I will do it later today / at weekend. Right now updating the surroundings first (CI etc.) which suffered a bit of the time.

**Comment by posidron** [comment]
Do you mean to reference to another variable inside of another variables section? Like in the following where `pc_r` requires the initialization of `pc_r` first?

Input:

```
%section% := value

dictContent :=
    a: null
    b: {}

dictObject :=
    {+dictContent+}

testStmnt :=
    !pc_l! = !pc_r!
    !pc_r! = !pc_l!

%section% := variable

pc_l :=
    let @pc_l@ = new +dictObject+

pc_r :=
    let @pc_r@ = !pc_x!

pc_x :=
    let @pc_x@ = new +dictObject+

%section% := variance

main :=
    +testStmnt+
```

Output:

```
let pc_l1 = new {a: null}
let pc_l2 = new {b: {}}

let pc_r1 = pc_x1
let pc_r2 = pc_x2

let pc_x1 = new {b: {}}
let pc_x2 = new {a: null}
```

In this case `pc_x` would need to be defined before `pc_r`.

**Comment by posidron** [comment]
Though, for this case I am almost inclined to say, set `pc_r` to `null` and assign later in the value section the value of `pc_x` to `pc_r`.

**Comment by posidron** [comment]
@shsirk Let me know if want to make a PR out of your current changes, otherwise I will push what I implemented from you above. In case of a PR, please add also a `DharmaConst.VARIABLE_MIN` and I would suggest changing the if condition to:

```
if self.count >= random.randint(DharmaConst.VARIABLE_MIN, DharmaConst.VARIABLE_MAX):
```

**Comment by shsirk** [comment]
@posidron sure, please push your changes. I will try to make PR of other stuff I am playing with if it fits with the simplicity of dharma. Thanks for this awesome tool 👍

**Comment by posidron** [comment]
Thank you, much appreciated.
