### ISSUE TITLE
-count flag does not work. It generates the same test cases.

### ISSUE THREAD

**Issue by DanilDelegator** [MozillaSecurity/dharma#14]

**Comment by dodaeche** [comment]
I have same issue with dharma 1.2.0.
When I set count option to 1 (and it's default value), dharma generate test case more than 1.
How can I get just 1 test case? Is there any other option flag ?

**Comment by posidron** [comment]
Hm, I can not reproduce this.

![Screen Shot 2019-10-21 at 3 32 05 PM](https://user-images.githubusercontent.com/1614333/67209614-f72f2d00-f417-11e9-976d-bd5e3efa4c30.png)
