### ISSUE TITLE
Throw errors when using 'common.dg' and 'svg.dg'.

### ISSUE THREAD

**Issue by ty5491003** [MozillaSecurity/dharma#19]
Hi，I just started using dharma and i met some problems:
When i run: `dharma -grammars dharma/grammars/common.dg -storage common -count 5`, i get error info:
```
[Dharma] 2019-11-28 21:40:30,732 INFO: Machine random seed: 5845788605360104063
[Dharma] 2019-11-28 21:40:30,732 DEBUG: Using configuration from: /export/nisl/.conda/envs/funfuzz/lib/python3.6/site-packages/dharma/settings.py
[Dharma] 2019-11-28 21:40:30,733 DEBUG: Processing grammar content of ../../.conda/envs/funfuzz/lib/python3.6/site-packages/dharma/grammars/common.dg
[Dharma] 2019-11-28 21:40:30,737 DEBUG: Processing grammar content of dharma/grammars/common.dg
[Dharma] 2019-11-28 21:40:30,737 ERROR: Line 8 [common](value): 'common:bool' gets redefined
```
And when i run: `dharma -grammars dharma/grammars/svg.dg -storage svg -count 5`, i get the error info:
```
[Dharma] 2019-11-28 21:32:47,487 INFO: Machine random seed: 8969750037613965213
[Dharma] 2019-11-28 21:32:47,487 DEBUG: Using configuration from: /export/nisl/.conda/envs/funfuzz/lib/python3.6/site-packages/dharma/settings.py
[Dharma] 2019-11-28 21:32:47,488 DEBUG: Processing grammar content of ../../.conda/envs/funfuzz/lib/python3.6/site-packages/dharma/grammars/common.dg
[Dharma] 2019-11-28 21:32:47,492 DEBUG: Processing grammar content of dharma/grammars/svg.dg
Segmentation fault (core dumped)
```
Except this two grammar files, others are worked as expected, So i want to know what is the reason. If i typed the command incorrectly, please let me know!
Thanks, looking forward your response.

**Comment by ty5491003** [comment]
@posidron Hi bro, Can you help me solve this issue?

**Comment by posidron** [comment]
@ty5491003 
Your first issue appears because `common.dg` is a helper grammar, it acts like a standard library and is imported for any grammar run but this grammar is not built for to run alone. If you run it alone, it would get also imported as the standard library grammar and hence the re-definition occurs.

The second issue seems because maximum recursion was reached for something inside the SVG grammar. I would need more time to further inspect this now but this could potentially be a bug in the grammar caused by the  https://github.com/MozillaSecurity/dharma/commit/4253e07389052f339e564e4c53586b55e7e8523f change and the lack of maintenance for that grammar.

**Comment by posidron** [comment]
@ty5491003 
I think I found the issue, could you pull and test if this works for you now? https://github.com/MozillaSecurity/dharma/commit/834203fc1bb7f99de5f88dd781e62f0089074ebd

**Comment by ty5491003** [comment]
I found the second issue is intermittent, I ran `dharma -grammars dharma/grammars/svg.dg` ten times and three times it worked and seven times it failed. (on the old code)

This bug persists when I use `834203f` version, so i think it doesn't work! @posidron

**Comment by ty5491003** [comment]
BTW, my testing system is `Ubuntu16.04`, and python version is `3.6.8`

**Comment by posidron** [comment]
Hm, are you really sure? 

```
posidron@syren~/D/dharma λ time python3 -m dharma -grammars dharma/grammars/svg.dg -count 10000 > /dev/null
[Dharma] 2019-12-05 03:11:37,819 INFO: Machine random seed: 8752282538948304095
[Dharma] 2019-12-05 03:11:37,819 DEBUG: Using configuration from: /Users/posidron/Downloads/dharma/dharma/settings.py
[Dharma] 2019-12-05 03:11:37,820 DEBUG: Processing grammar content of dharma/grammars/common.dg
[Dharma] 2019-12-05 03:11:37,824 DEBUG: Processing grammar content of dharma/grammars/svg.dg
       50.51 real        50.34 user         0.09 sys
posidron@syren~/D/dharma λ python3 --version
Python 3.7.5
```

I have not yet pushed the update as package to PyPi, may be you have run the installed PyPi version rather than the code from GitHub?

**Comment by ty5491003** [comment]
I'm sry, you are right!!! I run the wrong installed PyPi version. 

When I switch to the correct version, this bug disappeared. The update is worked! 

Thanks for your work.

**Comment by posidron** [comment]
Cool! A buddy of mine will push it tomorrow or so to PyPi.

**Comment by posidron** [comment]
FYI: v1.3.1 landed in PyPi
