### ISSUE TITLE
mention of dharma in fuzzing V8 WebAssembly JS APIs blogpost

### ISSUE THREAD

**Issue by pventuzelo** [MozillaSecurity/dharma#20]
Hi @posidron,

First of all thanks for dharma, awesome tool ;)
I just release a blogpost where i'm using it for fuzzing V8 WebAssembly JS APIs.

https://webassembly-security.com/fuzzing-wasm-javascript-dharma-chrome-v8/

Hope you will like it ;)

**Comment by posidron** [comment]
Nice! Are you willing to make a PR for the `wasm.dg`? You can put your information into the comment section.

**Comment by pventuzelo** [comment]
Oh yes sure ;) no prob !
