### ISSUE TITLE
Question: Submit dharma generated samples to FuzzManager

### ISSUE THREAD

**Issue by rc0r** [MozillaSecurity/dharma#4]
Hi  @MozillaSecurity and others,

I've successfully set up `dharma` + `quokka` + `FuzzManager` to fuzz Firefox nightly via websockets. However, when `quokka` detects a fault/crash only stdout/stderr/ASAN traces are submitted to `FuzzManager`. I'd also like to (automatically) collect the crash samples generated by `dharma` that cause the crash itself. (And only those samples, that are interesting.)

Is there a way to achieve just that using the `dharma`/`quokka`/`FuzzManager` setup?

**Comment by posidron** [comment]
There is not proper FuzzManager support yet. I became busy with other projects. :-( In general it is very easily possible.
https://github.com/MozillaSecurity/quokka/blob/master/core/loggers/fuzzmanager.py#L58 
https://github.com/MozillaSecurity/quokka/blob/master/core/listeners/testcase.py
