### ISSUE TITLE
How to configure Dharma?

### ISSUE THREAD

**Issue by greg5678** [MozillaSecurity/dharma#5]
I have looked in each file (including the settings.py file) but I have yet to see a configuration file. I would like to set the path of firefox but I see no where I can do that?

**Comment by jschwartzentruber** [comment]
Dharma is only for generating content. The fourth example in [README.md](https://github.com/MozillaSecurity/dharma#examples) shows how it can be used with a harness (Framboise, which is not released). You could also use it with your own harness for launching the browser or with something like [domInteresting.py](https://github.com/MozillaSecurity/funfuzz/blob/master/dom/automation/domInteresting.py).

For example:
`% ./dharma.py -server -grammars grammars/canvas2d.dg -template grammars/var/templates/html5/default.html`
(in parallel)
`% ./domInteresting.py /path/to/browserDir /path/to/dharma/dharma/grammars/var/index.html`

Note that this could run for a long time until a crash is found, which would make that crash hard to reproduce from the seed.

[Quokka](https://github.com/MozillaSecurity/quokka) is another harness you could use (also written by @posidron), but I have no experience using it.
